apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "clus-pv-role"
rules:
- apiGroups: [""]
  resources:
  - nodes
  - persistentvolumes
  - namespaces
  verbs: ["list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "clus-pv-role-bind"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "clus-pv-role"
subjects:
  - kind: ServiceAccount
    name: "azdev-sa-21fdcd"
    namespace: "default"